language: cpp
sudo: required
dist: trusty
cache: apt
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq cppcheck libfuse-dev openjdk-7-jdk
script:
 - ./autogen.sh
 - ./configure
 - make
 - make cppcheck
 - make check -C src
 - modprobe fuse
 - make check -C test
 - cat test/test-suite.log
